language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t talhaidrees/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true talhaidrees/react-test npm test -- --coverage

after_success:
  - docker build -t talhaidrees/multi-client ./client
  - docker build -t talhaidrees/multi-nginx ./nginx
  - docker build -t talhaidrees/multi-server ./server
  - docker build -t talhaidrees/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Inlist all images and push them to docker hub
  - docker push talhaidrees/multi-client:latest
  - docker push talhaidrees/multi-nginx:latest
  - docker push talhaidrees/multi-server:latest
  - docker push talhaidrees/multi-worker:latest